apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment-helm-chart.fullname" . }}
  labels:
    {{- include "deployment-helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
  {{- end }}
  selector:
    {{- include "deployment-helm-chart.selectorLabels" . | nindent 4 }}